const posts = [
              {
    "title": "The Attic Artist",
    "slug": "the-attic-artist",
    "desc": "A girl sitting on the floor of a sunlit attic, painting on a small canvas, surrounded by messy paint tubes and sketches.",
    "description": "A girl sitting on the floor of a sunlit attic, painting on a small canvas, surrounded by messy paint tubes and sketches.",
    "prompt": "Whimsical digital illustration of a girl painting on a canvas in a sunlit cozy attic, messy art supplies, scattered sketches, soft dust motes dancing in the light, warm inviting atmosphere, nostalgic aesthetic, soft painterly brushstrokes, detailed background, warm beige and pastel colors, storybook art style, highly detailed --ar 2:3\"",
    "image": "images/the-attic-artist.jpg",
    "tags": [],
    "category": "Art",
    "author": "Canvas Era",
    "date": "2026-08-15"
              },
            {
    "title": "Horus Wings Over Karnak",
    "slug": "horus-wings-over-karnak",
    "desc": "Woman among Karnak's columns, giant 2D comic Horus spreads his wings",
    "description": "Woman among Karnak's columns, giant 2D comic Horus spreads his wings",
    "prompt": "photorealistic smiling woman in flowing white linen sitting on an oriental rug between the towering carved columns of Karnak Temple, sunlight streaming through the stone pillars, giant friendly 2D black-and-white comic line-art of falcon-headed god Horus standing behind her with huge wings spread protectively around her, comic linework popping against the photoreal sandstone columns, cinematic golden hour lighting, warm dust particles, highly detailed --ar 9:16",
    "image": "images/horus-wings-over-karnak.jpg",
    "tags": [],
    "category": "Culture",
    "author": "Canvas Era",
    "date": "2026-08-15"
            },
          {
    "title": "Morning Tea in the Woods",
    "slug": "morning-tea-in-the-woods",
    "desc": "A girl sitting on a porch chair overlooking a misty forest, holding a warm cup of tea, with a peaceful expression.",
    "description": "A girl sitting on a porch chair overlooking a misty forest, holding a warm cup of tea, with a peaceful expression.",
    "prompt": "A beautiful digital illustration of a girl sitting in a wooden porch chair holding a steaming cup of tea, looking out at a serene misty forest, wearing a cozy oversized cardigan, soft morning lighting, intricate foliage, serene and peaceful expression, warm natural tones, soft lines, storybook illustration, highly detailed, whimsical and calm aesthetic --ar 2:3\"",
    "image": "images/morning-tea-in-the-woods.jpg",
    "tags": [],
    "category": "Art",
    "author": "Canvas Era",
    "date": "2026-08-15"
          },
        {
    "title": "Starlight Weaver",
    "slug": "starlight-weaver",
    "desc": "A goddess-like girl weaving starlight into the fabric of the night sky above a calm ocean.\n",
    "description": "A goddess-like girl weaving starlight into the fabric of the night sky above a calm ocean.\n",
    "prompt": "​Shoujo anime style, an elegant girl with flowing silver hair standing above a calm moonlit ocean, weaving glowing stardust threads into the sky, celestial jewelry, sparkles and magical light effects, dreamy and ethereal atmosphere, soft dreamy colors, intricate dress design, high quality, digital art, masterpiece --ar 2:3",
    "image": "images/starlight-weaver.jpg",
    "tags": [],
    "category": "Anime",
    "author": "Canvas Era",
    "date": "2026-08-15"
        },
      {
    "title": "The Magic Bakery",
    "slug": "the-magic-bakery",
    "desc": "A young girl preparing magical pastries in a cozy, sunlit kitchen filled with floating flour particles and glowing jars",
    "description": "A young girl preparing magical pastries in a cozy, sunlit kitchen filled with floating flour particles and glowing jars",
    "prompt": "​Anime style, cozy bakery kitchen interior, warm golden hour sunlight, a cute girl with braided hair baking magical sweets, floating flour dust particles, copper kitchen tools, soft and nostalgic aesthetic, Kyoto Animation style, highly detailed, vibrant and warm colors, masterpiece, peaceful mood --ar 4:5",
    "image": "images/the-magic-bakery.jpg",
    "tags": [],
    "category": "Anime",
    "author": "Canvas Era",
    "date": "2026-08-15"
      },
                {
    "title": "Ashurbanipal's Library ",
    "slug": "ashurbanipals-library",
    "desc": "Woman at Nineveh's ruins, giant comic Ashurbanipal reads her a ",
    "description": "Woman at Nineveh's ruins, giant comic Ashurbanipal reads her a ",
    "prompt": "photorealistic smiling woman in soft earth-tone robes sitting on an oriental rug amid the excavated ruins of Nineveh's royal library, broken clay tablets scattered artfully nearby, giant friendly 2D black-and-white comic line-art of King Ashurbanipal sitting behind her unrolling a huge scroll and reading aloud with a warm expression, comic linework contrasting the photoreal stone rubble, cinematic golden hour lighting, dust motes drifting, highly detailed --ar 9:16",
    "image": "images/ashurbanipals-library.jpg",
    "tags": [],
    "category": "Culture",
    "author": "Canvas Era",
    "date": "2026-08-15"
                },
            {
    "title": "Sargon's Palace Welcome",
    "slug": "sargons-palace-welcome",
    "desc": "Man in Nineveh's palace ruins, giant comic Sargon II welcomes him warmly",
    "description": "Man in Nineveh's palace ruins, giant comic Sargon II welcomes him warmly",
    "prompt": "photorealistic smiling man in a woven earth-tone robe sitting on an oriental rug inside the roofless ruins of an Assyrian palace, carved stone reliefs of hunting scenes visible on the walls behind him, giant friendly 2D black-and-white comic line-art of King Sargon II standing behind him with arms open wide in a warm welcoming gesture, comic linework contrasting the photoreal stone reliefs, cinematic golden hour lighting, dust particles in the air, highly detailed --ar 9:16",
    "image": "images/sargons-palace-welcome.jpg",
    "tags": [],
    "category": "Culture",
    "author": "Canvas Era",
    "date": "2026-08-15"
            },
          {
    "title": "Cozy Bookshop Bird Watcher",
    "slug": "cozy-bookshop-bird-watcher",
    "desc": "Messy-haired girl with cherry clips reads a bird book in a warm little bookshop",
    "description": "Messy-haired girl with cherry clips reads a bird book in a warm little bookshop",
    "prompt": "cozy bookshop girl with messy brown hair, cherry-shaped hair clips, round wire glasses, oversized cream cardigan, curled up in a window nook reading a large illustrated bird book, a small sparrow perched on her shoulder, towering wooden bookshelves and hanging plants around her, warm afternoon light through rain-speckled glass, Studio Ghibli meets children's storybook illustration, soft pastel palette, delicate ink linework, cozy warm atmosphere --ar 2:3",
    "image": "images/cozy-bookshop-bird-watcher.jpg",
    "tags": [],
    "category": "Art",
    "author": "Canvas Era",
    "date": "2026-08-15"
          },
        {
    "title": "Rooftop Stargazer and Cat",
    "slug": "rooftop-stargazer-and-cat",
    "desc": "Girl in a knit sweater stargazes on a cottage rooftop with her sleepy cat",
    "description": "Girl in a knit sweater stargazes on a cottage rooftop with her sleepy cat",
    "prompt": "cozy storybook girl with a loose braid and oversized knit sweater sitting on a slanted cottage rooftop, peering through a small brass telescope at a starry sky, a fluffy orange cat curled asleep beside her, warm string lights strung along the chimney, twinkling fireflies drifting near soft glowing windows below, Studio Ghibli meets children's book illustration, soft pastel palette, gentle ink linework, dreamy nighttime mood --ar 2:3",
    "image": "images/rooftop-stargazer-and-cat.jpg",
    "tags": [],
    "category": "Art",
    "author": "Canvas Era",
    "date": "2026-08-15"
        },
      {
    "title": "Rainy Window Letter Writer",
    "slug": "rainy-window-letter-writer",
    "desc": "Girl in a wool shawl writes a letter by candlelight as rain taps the window",
    "description": "Girl in a wool shawl writes a letter by candlelight as rain taps the window",
    "prompt": "cozy storybook girl with soft curly hair, thick wool shawl, sitting at a small wooden desk writing a letter by candlelight, a steaming teacup and pressed flowers beside her, rain streaking down the tall window overlooking a foggy little town, a curious cat watching from the windowsill, Studio Ghibli meets children's book illustration, soft pastel palette, gentle ink linework, quiet rainy-day mood --ar 2:3",
    "image": "images/rainy-window-letter-writer.jpg",
    "tags": [],
    "category": "Art",
    "author": "Canvas Era",
    "date": "2026-08-15"
      },
    {
    "title": "Hammurabi's Law Ziggurat",
    "slug": "hammurabis-law-ziggurat",
    "desc": "Man before a Babylon ziggurat, giant comic Hammurabi holds up his law code",
    "description": "Man before a Babylon ziggurat, giant comic Hammurabi holds up his law code",
    "prompt": "photorealistic smiling man in earth-toned robes sitting on a patterned oriental rug at the base of a reconstructed mudbrick ziggurat in ancient Babylon, warm terracotta tones and mudbrick texture, giant friendly 2D black-and-white comic line-art of King Hammurabi standing behind him proudly holding up a huge stone law tablet with a warm smile, playful scale contrast, cinematic golden hour lighting, dust haze over the plain, highly detailed photoreal and ink linework mix --ar 9:16",
    "image": "images/hammurabis-law-ziggurat.jpg",
    "tags": [],
    "category": "Culture",
    "author": "Canvas Era",
    "date": "2026-08-14"
    },
  {
    "title": "Cosmic Memory Portrait",
    "slug": "cosmic-memory-portrait",
    "desc": "A captivating digital oil painting of a woman merged with glowing cosmic nebula and golden floral elements.",
    "description": "A captivating digital oil painting of a woman merged with glowing cosmic nebula and golden floral elements.",
    "prompt": "Surreal digital portrait painting of a woman's side profile, blending seamlessly into a glowing galaxy nebula and gold leaf flowers, expressive brush strokes, dramatic chiaroscuro lighting, dark background, fine art style, trending on ArtStation --ar 3:4",
    "image": "images/cosmic-memory.jpg",
    "tags": [
      "Surreal",
      "Portrait",
      "Cosmic",
      "Oil Painting"
    ],
    "category": "Art",
    "author": "Canvas Era",
    "date": "2026-05-14"
  },
  {
    "title": "Neo-Kyo Cyber Fashion Icon",
    "slug": "neo-kyo-cyber-fashion-icon",
    "desc": "Futuristic cyberpunk anime portrait of a girl in high-tech streetwear with holographic visor in a neon-drenched rainy Tokyo night.",
    "description": "Futuristic cyberpunk anime portrait of a girl in high-tech streetwear with holographic visor in a neon-drenched rainy Tokyo night.",
    "prompt": "Cyberpunk fashion portrait, anime girl wearing a translucent futuristic visor and techwear jacket, vibrant neon bokeh background with city lights, soft rain streaks, blue and magenta color grading, sharp focus on expressive eyes, cinematic composition, futuristic urban aesthetic, masterpiece --ar 9:16",
    "image": "images/anime-cyber-fashion.jpg",
    "tags": [
      "Anime",
      "Cyberpunk",
      "Techwear",
      "Neon",
      "Futuristic"
    ],
    "category": "Anime",
    "author": "Canvas Era",
    "date": "2026-05-15"
  },
  {
    "title": "The Feathered Adventures - Cozy Bookshop Storybook Art",
    "slug": "cozy-bookshop-storybook-art",
    "desc": "Whimsical children's book illustration of a cozy bookshop girl reading about birds with warm pastel colors and storybook charm.",
    "description": "Whimsical children's book illustration of a cozy bookshop girl reading about birds with warm pastel colors and storybook charm.",
    "prompt": "A whimsical children's book illustration style artwork, a young girl with messy tousled blonde hair tied up with red cherry hair clips, wearing round oversized black glasses, sitting cross-legged on a windowsill in a cozy bookshop, reading an open picture book with colorful bird illustrations, wearing a striped long-sleeve shirt and rolled-up blue jeans with pink sneakers, surrounded by tall wooden bookshelves filled with colorful books, vintage bird illustration prints hanging on a mint-green wall, string lights with warm glowing bulbs hanging above, a small yellow toy bird chick sitting beside her, potted plants nearby, stacks of books on the floor, warm cozy lighting, soft pastel color palette, detailed ink linework with watercolor-style shading, adorable big-eyed character design, storybook illustration aesthetic --ar 2:3",
    "image": "images/cozy-bookshop-girl.jpg",
    "tags": [
      "Whimsical",
      "Children Book",
      "Cozy",
      "Storybook",
      "Illustration"
    ],
    "category": "Art",
    "author": "Canvas Era",
    "date": "2026-05-16"
  },
        {
    "title": "Fire Escape Cat Cyberpunk",
    "slug": "fire-escape-cat-cyberpunk",
    "desc": "Techwear girl and her cat watch neon rain from a fire ",
    "description": "Techwear girl and her cat watch neon rain from a fire ",
    "prompt": "cyberpunk girl with silver-streaked hair, oversized techwear jacket, sitting on a rusty fire escape with a small robotic cat curled beside her, rainy neon Tokyo alley glowing below with pink and blue signage, warm golden light spilling from her apartment window behind her, steam rising from a nearby vent, cozy plus futuristic mood, soft bokeh lights, cinematic detail --ar 9:16",
    "image": "images/fire-escape-cat-cyberpunk.jpg",
    "tags": [],
    "category": "Anime",
    "author": "Canvas Era",
    "date": "2026-08-15"
        },
  {
    "title": "Transform Your Photos with Ancient History and 2D Comic Style",
    "slug": "babylonian-king-thumbsup-mixed-media",
    "desc": "A friendly giant 2D Babylonian King gives a thumbs-up while hugging a real woman in ancient Babylonian ruins with Ziggurat view.",
    "description": "A unique blend of reality and imagination - merge high-detail photorealism with fun 2D black-and-white comic character in ancient Babylonian ruins.",
    "prompt": "A striking mixed-media photograph of a smiling young woman sitting cross-legged on an ancient oriental rug amidst stone ruins with a distant Ziggurat. Behind her stands a giant, friendly 2D comic line-art illustration of an Ancient Babylonian King with a cuneiform-engraved gold crown and braided square beard, hugging her playfully and giving an enthusiastic thumbs-up. Warm golden hour lighting, strong visual contrast between photorealistic environment and 2D ink line-art character, high resolution, cinematic composition --ar 9:16",
    "image": "images/babylon-king-thumbsup.jpg",
    "tags": [
      "Babylonian",
      "Mixed Media",
      "Ziggurat",
      "Ancient History",
      "Comic"
    ],
    "category": "Culture",
    "author": "Canvas Era",
    "date": "2026-05-17"
  },
        {
    "title": "Cottage Kitchen Bread",
    "slug": "cottage-kitchen-bread",
    "desc": "Apron-clad girl kneads dough in a flour-dusted cottage kitchen at sunrise",
    "description": "Apron-clad girl kneads dough in a flour-dusted cottage kitchen at sunrise",
    "prompt": "cozy storybook girl with pigtail buns, flour-dusted apron, sleeves rolled up, kneading bread dough on a wooden table in a warm cottage kitchen, copper pots hanging above, a small mouse peeking from a bread basket, morning sunlight streaming through a herb-filled windowsill, Studio Ghibli meets children's book illustration, soft pastel palette, delicate ink linework, warm nostalgic mood --ar 2:3",
    "image": "images/cottage-kitchen-bread.jpg",
    "tags": [],
    "category": "Art",
    "author": "Canvas Era",
    "date": "2026-08-15"
        },
    {
    "title": "Midnight Neon Dreamer",
    "slug": "midnight-neon-dreamer",
    "desc": "A futuristic girl with cybernetic gear sitting on a fire escape, overlooking a rain-soaked, neon-lit metropolis",
    "description": "A futuristic girl with cybernetic gear sitting on a fire escape, overlooking a rain-soaked, neon-lit metropolis",
    "prompt": "​Cyberpunk anime portrait, a girl wearing futuristic cybernetic headphones and a techwear jacket, sitting on a fire escape, rainy night in a futuristic metropolis, reflection of neon signs in wet puddles, soft bokeh city lights in the background, synthwave color palette (neon blue and pink), moody lighting, sharp focus on eyes, ultra-detailed, futuristic urban aesthetic --ar 9:16",
    "image": "images/midnight-neon-dreamer.jpg",
    "tags": [],
    "category": "Anime",
    "author": "Canvas Era",
    "date": "2026-08-14"
    },
  {
    "title": "Bring Ancient Egyptian Mythology to Life with Mixed-Media AI Art",
    "slug": "egyptian-anubis-guardian-mixed-media",
    "desc": "Photorealistic woman sketching in Egyptian desert with a giant friendly 2D Anubis guardian smiling behind her at golden sunset.",
    "description": "Creative mixed-media concept blending stunning realism of a desert photograph with fun illustrative style of a 2D comic Anubis guardian.",
    "prompt": "A realistic photo of a smiling young woman sitting cross-legged on a small vintage oriental rug on the desert sand, holding a sketchbook and pen. Ancient Egyptian pyramid ruins are in the background during a beautiful golden sunset. Behind her, a giant cute 2D cartoon illustration of Anubis with black jackal ears and an Egyptian collar, drawn in clean 2D black-and-white comic line-art style. The cartoon Anubis is acting as a gentle protective guardian, resting his hands softly near her shoulders with a big, wholesome, friendly smile. Mixed media art, real photograph combined with a 2D cartoon drawing, high contrast, cinematic lighting, highly detailed --ar 9:16",
    "image": "images/egypt-anubis-guardian.jpg",
    "tags": [
      "Egyptian",
      "Anubis",
      "Mixed Media",
      "Pyramids",
      "Ancient Egypt"
    ],
    "category": "Culture",
    "author": "Canvas Era",
    "date": "2026-05-18"
  },
    {
    "title": "Rainy Day Serenity: A Childhood Memory",
    "slug": "rainy-day-serenity-a-childhood-memory",
    "desc": "Embrace the comfort of a rainy afternoon with this enchanting illustration. Featuring a joyful girl and her faithful white cat amidst a garden of blooming roses, this piece perfectly captures the innocence, warmth, and nostalgia of childhood on a gentle rainy day.",
    "description": "Embrace the comfort of a rainy afternoon with this enchanting illustration. Featuring a joyful girl and her faithful white cat amidst a garden of blooming roses, this piece perfectly captures the innocence, warmth, and nostalgia of childhood on a gentle rainy day.",
    "prompt": "A charming illustration of a joyful little girl with long black hair, smiling, wearing a white dress with red polka dots and red rain boots. She is standing in a lush rose garden, holding a vibrant multi-colored umbrella. A cute white cat sits beside her looking up. Rainy day ambiance, light beige sky background. Art Style: Xiaohongshu illustration style, clear black outlines, warm earth tones (beige, red, dark green), richly detailed roses and foliage, flat illustration style, soft lighting, no harsh shadows, whimsical, 8k, high quality, professional art --ar 2:3",
    "image": "images/rainy-day-serenity-a-childhood-memory.jpg",
    "tags": [],
    "category": "Art",
    "author": "Canvas Era",
    "date": "2026-08-14"
    },
    {
    "title": "Alchemist's Cozy Corner",
    "slug": "alchemists-cozy-corner",
    "desc": "A cozy, cluttered room filled with glowing potion bottles, ancient books, and a little cat wearing a wizard hat",
    "description": "A cozy, cluttered room filled with glowing potion bottles, ancient books, and a little cat wearing a wizard hat",
    "prompt": "​Anime illustration, interior of a cozy witch's alchemy workshop, shelves stacked with glowing colorful potion jars and leather-bound books, soft golden light filtering through a stained glass window, a cute small black cat wearing a tiny wizard hat sitting on a desk, whimsical and magical atmosphere, warm tones, Studio Pierrot style, highly detailed, vibrant colors --ar 4:5",
    "image": "images/alchemists-cozy-corner.jpg",
    "tags": [],
    "category": "Anime",
    "author": "Canvas Era",
    "date": "2026-08-14"
    },
  {
    "title": "Embrace the Power of Assyrian Mythology with Mixed-Media AI Art",
    "slug": "assyrian-lamassu-mixed-media",
    "desc": "A beautiful blend of realistic photography and Assyrian heritage. A guardian Lamassu drawn in elegant ink protects the modern muse.",
    "description": "A beautiful blend of realistic photography and Assyrian heritage. A guardian Lamassu drawn in elegant ink protects the modern muse.",
    "prompt": "A realistic cinematic photograph of a smiling young woman sitting relaxed on ancient stone steps. Standing protectively behind her is a giant 2D cartoon illustration of a majestic Assyrian Winged Bull (Lamassu). The Lamassu is drawn in clean, thick black ink line art comic style. It features the authentic ancient bearded human face with a squared braided beard and a horned crown, but stylized beautifully and elegantly. The 2D Lamassu acts as a noble guardian, with its large grand wing gently curving behind the woman's back like a protective shield. Mixed media composition, photo-realism blended with 2D ink illustration, dramatic natural lighting, highly detailed --ar 9:16",
    "image": "images/lamassu-guardian.jpg",
    "tags": [
      "Mixed Media",
      "Assyrian",
      "Lamassu"
    ],
    "category": "Culture",
    "author": "Canvas Era",
    "date": "2026-05-13"
  },
          {
    "title": "The Greenhouse Botanist",
    "slug": "the-greenhouse-botanist",
    "desc": "A gentle boy tending to his lush indoor greenhouse, surrounded by hanging plants, sunlight, and a small watering can.",
    "description": "A gentle boy tending to his lush indoor greenhouse, surrounded by hanging plants, sunlight, and a small watering can.",
    "prompt": "Soft digital illustration of a young boy in a sweater tending to an indoor greenhouse, lush hanging plants and vines everywhere, sunbeams streaming through glass windows, cozy cottage-core aesthetic, warm golden light, gentle expression, detailed botanical elements, clean soft lines, warm earth tones, storybook illustration style, high quality --ar 2:3",
    "image": "images/the-greenhouse-botanist.jpg",
    "tags": [],
    "category": "Art",
    "author": "Canvas Era",
    "date": "2026-08-15"
  },
        {
    "title": "The Clockmaker's Apprentice",
    "slug": "the-clockmakers-apprentice",
    "desc": "A boy sitting at a desk filled with gears and clocks, working with a small tool under the warm light of a desk lamp.",
    "description": "A boy sitting at a desk filled with gears and clocks, working with a small tool under the warm light of a desk lamp.",
    "prompt": "Charming digital illustration of a young boy working on a vintage wooden clock at a cluttered wooden desk, surrounded by gears and tools, warm amber desk lamp lighting, cozy rustic workshop, soft shadows, intricate details, gentle focus, warm color palette (browns, creams, gold), storybook illustration, peaceful and focused atmosphere --ar 4:5\"",
    "image": "images/the-clockmakers-apprentice.jpg",
    "tags": [],
    "category": "Art",
    "author": "Canvas Era",
    "date": "2026-08-15"
          },
    {
    "title": "Lamassu Guardian Thumbs Up",
    "slug": "lamassu-guardian-thumbs-up",
    "desc": "Man beside a stone lamassu, giant comic Ashurbanipal gives a thumbs up",
    "description": "Man beside a stone lamassu, giant comic Ashurbanipal gives a thumbs up",
    "prompt": "photorealistic smiling man in simple linen tunic sitting on a woven oriental rug beside the massive stone winged-bull lamassu statue at the gates of ancient Nineveh, weathered limestone texture and cuneiform carvings visible, giant friendly 2D black-and-white comic line-art of King Ashurbanipal standing tall behind him giving an enthusiastic thumbs up with a huge grin, playful scale contrast between comic king and real ruins, cinematic golden hour light raking across the stone, dust motes, highly detailed photoreal and ink linework mix --ar 9:16",
    "image": "images/lamassu-guardian-thumbs-up.jpg",
    "tags": [],
    "category": "Culture",
    "author": "Canvas Era",
    "date": "2026-08-14"
    },
    {
    "title": "Magical Café in Floating Islands",
    "slug": "magical-caf-in-floating-islands",
    "desc": "A cozy fantasy coffee shop perched on a floating island above the clouds, serving magical creatures.",
    "description": "A cozy fantasy coffee shop perched on a floating island above the clouds, serving magical creatures.",
    "prompt": "A charming anime-style café built on a floating island above cotton candy clouds, outdoor terrace with wooden tables and magical floating lanterns, a friendly witch barista serving glowing latte art to a small dragon and a cat familiar, whimsical fantasy architecture with climbing ivy and flower boxes, sunset golden hour lighting, vibrant colors, detailed background with other floating islands visible, cozy atmosphere, Kyoto Animation style --ar 4:3",
    "image": "images/magical-caf-in-floating-islands.jpg",
    "tags": [],
    "category": "Anime",
    "author": "Canvas Era",
    "date": "2026-08-14"
    },
          
  
];
