const posts = [
      {
    "title": "Crimson Heritage Portrait",
    "slug": "crimson-heritage-portrait",
    "desc": "A breathtaking portrait of a beautiful woman in traditional embroidered clothing, holding a bowl of fresh fruit against a richly detailed floral tapestry background.",
    "description": "A breathtaking portrait of a beautiful woman in traditional embroidered clothing, holding a bowl of fresh fruit against a richly detailed floral tapestry background.",
    "prompt": "A highly detailed, stylized digital illustration of a beautiful young woman with long, flowing dark hair and blonde highlights. She has large expressive brown eyes, prominent winged eyeliner, rosy cheeks, and red lips. She is wearing a large, ornate traditional round earring with a red gemstone. She gracefully holds a decorative blue and gold bowl filled with red pomegranate seeds, berries, and slices of watermelon. Her dress is an elegant, wide-necked cream garment covered in intricate, traditional floral and botanical patterns in red, blue, and gold. The background is dark and densely packed with rich, flat-style folk-art floral motifs, mandalas, and vibrant botanical elements. Rich warm colors, high contrast, 2D flat art style blended with modern character design, masterpiece, highly aesthetic.\n9:16",
    "image": "images/crimson-heritage-portrait.jpg",
    "tags": [],
    "category": "Art",
    "author": "Canvas Era",
    "date": "2026-08-29"
      },
     {
    "title": "Anime Heritage Tapestry",
    "slug": "anime-heritage-tapestry",
    "desc": "A beautiful anime-style portrait of a girl in traditional embroidered clothing, holding fresh pomegranates against a rich floral tapestry background.",
    "description": "A beautiful anime-style portrait of a girl in traditional embroidered clothing, holding fresh pomegranates against a rich floral tapestry background.",
    "prompt": "​A beautiful anime girl in the style of Kyoto Animation, wearing an intricately embroidered traditional dress, holding a bowl of fresh pomegranates. The background is a rich, highly detailed floral tapestry with deep reds, golds, and midnight blues. Masterpiece anime illustration, vibrant colors, cultural aesthetic, 8k --ar 9:16",
    "image": "images/anime-heritage-tapestry.jpg",
    "tags": [],
    "category": "Anime",
    "author": "Canvas Era",
    "date": "2026-08-29"
     },
    {
    "title": "Istanbul Memories — Across Two Worlds",
    "slug": "istanbul-memories-across-two-worlds",
    "desc": "A warm Istanbul escape filled with colorful bazaars, ferry rides, historic mosques, Turkish tea, and softly preserved travel memories.",
    "description": "A warm Istanbul escape filled with colorful bazaars, ferry rides, historic mosques, Turkish tea, and softly preserved travel memories.",
    "prompt": "Cozy travel scrapbook collage of a cute young girl traveling through Istanbul, Turkey, surrounded by vintage ferry tickets, Turkish postage stamps, polaroid snapshots, handwritten travel notes, decorative paper scraps, dried flowers, tea receipts, Blue Mosque, Hagia Sophia, Galata Tower, Bosphorus ferry, Grand Bazaar and colorful Ottoman architecture, warm terracotta, cream and dusty blue palette, soft afternoon sunlight, textured handmade paper, layered vintage scrapbook composition, nostalgic travel journal feeling, highly detailed illustration, dreamy cozy atmosphere --ar 2:3",
    "image": "images/istanbul-memories-across-two-worlds.jpg",
    "tags": [],
    "category": "Cities",
    "author": "Canvas Era",
    "date": "2026-08-22"
    },
   {
    "title": "Warm Hearth & Heavy Rain",
    "slug": "warm-hearth-heavy-rain",
    "desc": " A peaceful moment by the window seat, featuring a classic wood-burning fireplace, soft candlelight, and cozy rainy day aesthetics.",
    "description": " A peaceful moment by the window seat, featuring a classic wood-burning fireplace, soft candlelight, and cozy rainy day aesthetics.",
    "prompt": "A cozy digital illustration of a beautiful young woman with voluminous curly brown hair adorned with small pastel flowers. She is wearing a soft, heather-gray fleece-lined lounge top and dark striped lounge pants, sitting barefoot on a wooden window seat. She has her eyes closed, smiling peacefully, resting her chin in her hands with her knees pulled up. Next to her is a classic cast-iron wood-burning fireplace with a bright roaring fire. Outside the large window, heavy rain is falling with cool moody tones. The scene is detailed with a potted green plant, a small bird perched on the sill, a vintage lantern with a glowing candle, small standalone candles, and ONE single, unique, antique-style ceramic coffee mug (matching the style from the original) filled with coffee. Crucially, only one cup is present. Contrast between cool rainy light and warm orange firelight, cozy storybook art style, highly detailed, whimsical, soft lighting.",
    "image": "images/warm-hearth-heavy-rain.jpg",
    "tags": [],
    "category": "Art",
    "author": "Canvas Era",
    "date": "2026-08-22"
   },
              {
    "title": "The Attic Artist",
    "slug": "the-attic-artist",
    "desc": "A girl sitting on the floor of a sunlit attic, painting on a small canvas, surrounded by messy paint tubes and sketches.",
    "description": "A girl sitting on the floor of a sunlit attic, painting on a small canvas, surrounded by messy paint tubes and sketches.",
    "prompt": "Whimsical digital illustration of a girl painting on a canvas in a sunlit cozy attic, messy art supplies, scattered sketches, soft dust motes dancing in the light, warm inviting atmosphere, nostalgic aesthetic, soft painterly brushstrokes, detailed background, warm beige and pastel colors, storybook art style, highly detailed --ar 2:3",
    "image": "images/the-attic-artist.jpg",
    "tags": ["cozy", "art studio", "ghibli"],
    "category": "Art",
    "author": "Canvas Era",
    "date": "2026-08-15"
              },
    {
    "title": "Seoul in Bloom — Korean Travel Scrapbook",
    "slug": "seoul-in-bloom-korean-travel-scrapbook",
    "desc": "A dreamy Seoul adventure blending ancient palaces, cozy cafés, colorful streets, cherry blossoms, and cherished moments captured on paper.",
    "description": "A dreamy Seoul adventure blending ancient palaces, cozy cafés, colorful streets, cherry blossoms, and cherished moments captured on paper.",
    "prompt": "Cozy travel scrapbook collage of a cute young girl exploring Seoul, South Korea, surrounded by vintage subway tickets, Korean postage stamps, polaroid photographs, handwritten Korean travel notes, café receipts, delicate washi tape, pressed cherry blossoms, traditional paper fragments, Gyeongbokgung Palace, Bukchon Hanok Village, N Seoul Tower, Han River, colorful Insadong streets and charming Korean cafés, warm ivory, dusty pink and muted sage palette, soft golden afternoon lighting, subtle city reflections, textured vintage paper, layered torn scrapbook elements, nostalgic Korean travel journal aesthetic, highly detailed illustration, whimsical cozy atmosphere, dreamy cinematic softness --ar 2:3",
    "image": "images/seoul-in-bloom-korean-travel-scrapbook.jpg",
    "tags": [],
    "category": "Cities",
    "author": "Canvas Era",
    "date": "2026-08-22"
    },
          {
    "title": "Morning Tea in the Woods",
    "slug": "morning-tea-in-the-woods",
    "desc": "A girl sitting on a porch chair overlooking a misty forest, holding a warm cup of tea, with a peaceful expression.",
    "description": "A girl sitting on a porch chair overlooking a misty forest, holding a warm cup of tea, with a peaceful expression.",
    "prompt": "A beautiful digital illustration of a girl sitting in a wooden porch chair holding a steaming cup of tea, looking out at a serene misty forest, wearing a cozy oversized cardigan, soft morning lighting, intricate foliage, serene and peaceful expression, warm natural tones, soft lines, storybook illustration, highly detailed, whimsical and calm aesthetic --ar 2:3",
    "image": "images/morning-tea-in-the-woods.jpg",
    "tags": ["cozy", "forest", "morning"],
    "category": "Art",
    "author": "Canvas Era",
    "date": "2026-08-15"
          },
        {
    "title": "Starlight Weaver",
    "slug": "starlight-weaver",
    "desc": "A goddess-like girl weaving starlight into the fabric of the night sky above a calm ocean.\n",
    "description": "A goddess-like girl weaving starlight into the fabric of the night sky above a calm ocean.\n",
    "prompt": "​Shoujo anime style, an elegant girl with flowing silver hair standing above a calm moonlit ocean, weaving glowing stardust threads into the sky, celestial jewelry, sparkles and magical light effects, dreamy and ethereal atmosphere, soft dreamy colors, intricate dress design, high quality, digital art, masterpiece --ar 2:3",
    "image": "images/starlight-weaver.jpg",
    "tags": [],
    "category": "Anime",
    "author": "Canvas Era",
    "date": "2026-08-15"
        },
    {
    "title": "Venice in a Daydream — Italian Scrapbook",
    "slug": "venice-in-a-daydream-italian-scrapbook",
    "desc": "A romantic Venice escape drifting through canals, bridges, colorful buildings, quiet cafés, and timeless moments preserved on paper.",
    "description": "A romantic Venice escape drifting through canals, bridges, colorful buildings, quiet cafés, and timeless moments preserved on paper.",
    "prompt": "Cozy travel scrapbook collage of a cute young girl traveling through Venice, Italy, surrounded by vintage Vaporetto tickets, Italian postcards, polaroid photographs, handwritten notes, postage stamps, café receipts, delicate lace, pressed flowers, Rialto Bridge, Grand Canal, St. Mark's Basilica, gondolas and colorful Venetian buildings, warm ivory, dusty rose and muted teal palette, soft golden afternoon light, aged paper textures, layered torn scrapbook elements, nostalgic European travel journal aesthetic, highly detailed illustration, dreamy romantic atmosphere, gentle cinematic lighting --ar 2:3",
    "image": "images/venice-in-a-daydream-italian-scrapbook.jpg",
    "tags": [],
    "category": "Cities",
    "author": "Canvas Era",
    "date": "2026-08-22"
    },
      {
    "title": "The Magic Bakery",
    "slug": "the-magic-bakery",
    "desc": "A young girl preparing magical pastries in a cozy, sunlit kitchen filled with floating flour particles and glowing jars",
    "description": "A young girl preparing magical pastries in a cozy, sunlit kitchen filled with floating flour particles and glowing jars",
    "prompt": "​Anime style, cozy bakery kitchen interior, warm golden hour sunlight, a cute girl with braided hair baking magical sweets, floating flour dust particles, copper kitchen tools, soft and nostalgic aesthetic, Kyoto Animation style, highly detailed, vibrant and warm colors, masterpiece, peaceful mood --ar 4:5",
    "image": "images/the-magic-bakery.jpg",
    "tags": [],
    "category": "Anime",
    "author": "Canvas Era",
    "date": "2026-08-15"
      },
          {
    "title": "Cozy Bookshop Bird Watcher",
    "slug": "cozy-bookshop-bird-watcher",
    "desc": "Messy-haired girl with cherry clips reads a bird book in a warm little bookshop",
    "description": "Messy-haired girl with cherry clips reads a bird book in a warm little bookshop",
    "prompt": "cozy bookshop girl with messy brown hair, cherry-shaped hair clips, round wire glasses, oversized cream cardigan, curled up in a window nook reading a large illustrated bird book, a small sparrow perched on her shoulder, towering wooden bookshelves and hanging plants around her, warm afternoon light through rain-speckled glass, Studio Ghibli meets children's storybook illustration, soft pastel palette, delicate ink linework, cozy warm atmosphere --ar 2:3",
    "image": "images/cozy-bookshop-bird-watcher.jpg",
    "tags": [],
    "category": "Art",
    "author": "Canvas Era",
    "date": "2026-08-15"
          },
   {
    "title": "Sydney Sunsets — Australian Travel Scrapbook",
    "slug": "sydney-sunsets-australian-travel-scrapbook",
    "desc": "A sunny Sydney adventure filled with harbor views, colorful beaches, charming cafés, iconic landmarks, and treasured travel memories.",
    "description": "A sunny Sydney adventure filled with harbor views, colorful beaches, charming cafés, iconic landmarks, and treasured travel memories.",
    "prompt": "Cozy travel scrapbook collage of a cute young girl exploring Sydney, Australia, surrounded by vintage ferry tickets, Australian postage stamps, polaroid photographs, handwritten travel notes, café receipts, seashells, pressed flowers, torn paper fragments, Sydney Opera House, Sydney Harbour Bridge, Bondi Beach, colorful coastal houses and a charming harbor ferry, warm ivory, sandy beige and muted turquoise palette, soft golden sunset lighting, subtle ocean reflections, textured vintage paper, layered scrapbook elements, nostalgic Australian travel journal aesthetic, highly detailed illustration, whimsical cozy atmosphere, dreamy cinematic softness --ar 2:3",
    "image": "images/sydney-sunsets-australian-travel-scrapbook.jpg",
    "tags": [],
    "category": "Cities",
    "author": "Canvas Era",
    "date": "2026-08-22"
   },
        {
    "title": "Rooftop Stargazer and Cat",
    "slug": "rooftop-stargazer-and-cat",
    "desc": "Girl in a knit sweater stargazes on a cottage rooftop with her sleepy cat",
    "description": "Girl in a knit sweater stargazes on a cottage rooftop with her sleepy cat",
    "prompt": "cozy storybook girl with a loose braid and oversized knit sweater sitting on a slanted cottage rooftop, peering through a small brass telescope at a starry sky, a fluffy orange cat curled asleep beside her, warm string lights strung along the chimney, twinkling fireflies drifting near soft glowing windows below, Studio Ghibli meets children's book illustration, soft pastel palette, gentle ink linework, dreamy nighttime mood --ar 2:3",
    "image": "images/rooftop-stargazer-and-cat.jpg",
    "tags": [],
    "category": "Art",
    "author": "Canvas Era",
    "date": "2026-08-15"
        },
      {
    "title": "Rainy Window Letter Writer",
    "slug": "rainy-window-letter-writer",
    "desc": "Girl in a wool shawl writes a letter by candlelight as rain taps the window",
    "description": "Girl in a wool shawl writes a letter by candlelight as rain taps the window",
    "prompt": "cozy storybook girl with soft curly hair, thick wool shawl, sitting at a small wooden desk writing a letter by candlelight, a steaming teacup and pressed flowers beside her, rain streaking down the tall window overlooking a foggy little town, a curious cat watching from the windowsill, Studio Ghibli meets children's book illustration, soft pastel palette, gentle ink linework, quiet rainy-day mood --ar 2:3",
    "image": "images/rainy-window-letter-writer.jpg",
    "tags": [],
    "category": "Art",
    "author": "Canvas Era",
    "date": "2026-08-15"
      },
    {
    "title": "Tokyo Dreaming — A Scrapbook Journey",
    "slug": "tokyo-dreaming-a-scrapbook-journey",
    "desc": "A playful Tokyo adventure blending neon nights, quiet temples, delicious treats, and treasured moments captured between scrapbook pages.",
    "description": "A playful Tokyo adventure blending neon nights, quiet temples, delicious treats, and treasured moments captured between scrapbook pages.",
    "prompt": "Cozy travel scrapbook collage of a cute young girl exploring Tokyo, Japan, surrounded by vintage train tickets, Japanese postage stamps, polaroid photographs, handwritten journal notes, washi tape, tiny ramen receipts, cherry blossom petals, paper textures, Tokyo Tower, Shibuya Crossing, Senso-ji Temple, traditional lanterns and colorful streets of Harajuku, warm cream and muted coral palette with subtle neon accents, soft evening lighting, layered travel journal composition, nostalgic paper collage, highly detailed illustration, charming whimsical atmosphere, cozy cinematic aesthetic --ar 2:3",
    "image": "images/tokyo-dreaming-a-scrapbook-journey.webp",
    "tags": [],
    "category": "Cities",
    "author": "Canvas Era",
    "date": "2026-08-30"
    },
   {
    "title": "Cosmic Memory Portrait",
    "slug": "cosmic-memory-portrait",
    "desc": "A captivating digital oil painting of a woman merged with glowing cosmic nebula and golden floral elements.",
    "description": "A captivating digital oil painting of a woman merged with glowing cosmic nebula and golden floral elements.",
    "prompt": "Surreal digital portrait painting of a woman's side profile, blending seamlessly into a glowing galaxy nebula and gold leaf flowers, expressive brush strokes, dramatic chiaroscuro lighting, dark background, fine art style, trending on ArtStation --ar 3:4",
    "image": "images/cosmic-memory-portrait.webp",
    "tags": [],
    "category": "Art",
    "author": "Canvas Era",
    "date": "2026-08-30"
   },
   {
    "title": "Neo-Kyo Cyber Fashion Icon",
    "slug": "neo-kyo-cyber-fashion-icon",
    "desc": "Futuristic cyberpunk anime portrait of a girl in high-tech streetwear with holographic visor in a neon-drenched rainy Tokyo night.",
    "description": "Futuristic cyberpunk anime portrait of a girl in high-tech streetwear with holographic visor in a neon-drenched rainy Tokyo night.",
    "prompt": "Cyberpunk fashion portrait, anime girl wearing a translucent futuristic visor and techwear jacket, vibrant neon bokeh background with city lights, soft rain streaks, blue and magenta color grading, sharp focus on expressive eyes, cinematic composition, futuristic urban aesthetic, masterpiece --ar 9:16",
    "image": "images/neo-kyo-cyber-fashion-icon.webp",
    "tags": [],
    "category": "Anime",
    "author": "Canvas Era",
    "date": "2026-08-30"
   },
   {
    "title": "The Feathered Adventures - Cozy Bookshop Storybook Art",
    "slug": "the-feathered-adventures-cozy-bookshop-storybook-art",
    "desc": "Whimsical children's book illustration of a cozy bookshop girl reading about birds with warm pastel colors and storybook charm.",
    "description": "Whimsical children's book illustration of a cozy bookshop girl reading about birds with warm pastel colors and storybook charm.",
    "prompt": "A whimsical children's book illustration style artwork, a young girl with messy tousled blonde hair tied up with red cherry hair clips, wearing round oversized black glasses, sitting cross-legged on a windowsill in a cozy bookshop, reading an open picture book with colorful bird illustrations, wearing a striped long-sleeve shirt and rolled-up blue jeans with pink sneakers, surrounded by tall wooden bookshelves filled with colorful books, vintage bird illustration prints hanging on a mint-green wall, string lights with warm glowing bulbs hanging above, a small yellow toy bird chick sitting beside her, potted plants nearby, stacks of books on the floor, warm cozy lighting, soft pastel color palette, detailed ink linework with watercolor-style shading, adorable big-eyed character design, storybook illustration aesthetic --ar 2:3",
    "image": "images/the-feathered-adventures-cozy-bookshop-storybook-art.webp",
    "tags": [],
    "category": "Art",
    "author": "Canvas Era",
    "date": "2026-08-30"
   },
       {
    "title": "New York Moments — City Lights Scrapbook",
    "slug": "new-york-moments-city-lights-scrapbook",
    "desc": "A cozy New York adventure capturing bright city streets, iconic skyscrapers, coffee breaks, subway rides, and spontaneous little memories.",
    "description": "A cozy New York adventure capturing bright city streets, iconic skyscrapers, coffee breaks, subway rides, and spontaneous little memories.",
    "prompt": "Cozy travel scrapbook collage of a cute young girl exploring New York City, surrounded by vintage subway tickets, polaroid photographs, handwritten notes, old receipts, postage stamps, coffee shop stickers, pressed paper scraps, Statue of Liberty, Empire State Building, Brooklyn Bridge, Times Square and Central Park, warm cream and muted caramel palette with subtle city-light accents, soft golden-hour lighting, textured vintage paper, layered scrapbook composition, nostalgic urban travel journal aesthetic, highly detailed illustration, charming cozy atmosphere, cinematic softness --ar 2:3",
    "image": "images/new-york-moments-city-lights-scrapbook.webp",
    "tags": [],
    "category": "Cities",
    "author": "Canvas Era",
    "date": "2026-08-30"
       },
         {
    "title": "Fire Escape Cat Cyberpunk",
    "slug": "fire-escape-cat-cyberpunk",
    "desc": "Techwear girl and her cat watch neon rain from a fire",
    "description": "Techwear girl and her cat watch neon rain from a fire",
    "prompt": "cyberpunk girl with silver-streaked hair, oversized techwear jacket, sitting on a rusty fire escape with a small robotic cat curled beside her, rainy neon Tokyo alley glowing below with pink and blue signage, warm golden light spilling from her apartment window behind her, steam rising from a nearby vent, cozy plus futuristic mood, soft bokeh lights, cinematic detail --ar 9:16",
    "image": "images/fire-escape-cat-cyberpunk.webp",
    "tags": [],
    "category": "Anime",
    "author": "Canvas Era",
    "date": "2026-08-30"
         },
         {
    "title": "Cottage Kitchen Bread",
    "slug": "cottage-kitchen-bread",
    "desc": "Apron-clad girl kneads dough in a flour-dusted cottage kitchen at sunrise",
    "description": "Apron-clad girl kneads dough in a flour-dusted cottage kitchen at sunrise",
    "prompt": "cozy storybook girl with pigtail buns, flour-dusted apron, sleeves rolled up, kneading bread dough on a wooden table in a warm cottage kitchen, copper pots hanging above, a small mouse peeking from a bread basket, morning sunlight streaming through a herb-filled windowsill, Studio Ghibli meets children's book illustration, soft pastel palette, delicate ink linework, warm nostalgic mood --ar 2:3",
    "image": "images/cottage-kitchen-bread.webp",
    "tags": [],
    "category": "Art",
    "author": "Canvas Era",
    "date": "2026-08-30"
  },
    {
    "title": "London Calling — Rainy Day Scrapbook",
    "slug": "london-calling-rainy-day-scrapbook",
    "desc": "A charming London adventure with rainy streets, red buses, cozy cafés, historic landmarks, and little memories tucked between pages.",
    "description": "A charming London adventure with rainy streets, red buses, cozy cafés, historic landmarks, and little memories tucked between pages.",
    "prompt": "Cozy travel scrapbook collage of a cute young girl exploring London, England, surrounded by vintage Underground tickets, old postcards, polaroid photographs, handwritten notes, postage stamps, tea tags, paper receipts, Big Ben, Tower Bridge, red double-decker bus, London Eye, Westminster Palace and charming Notting Hill streets, warm beige and muted burgundy palette, soft rainy daylight, subtle reflections, layered torn-paper textures, vintage travel journal aesthetic, highly detailed illustration, whimsical cozy atmosphere, nostalgic cinematic lighting --ar 2:3",
    "image": "images/london-calling-rainy-day-scrapbook.webp",
    "tags": [],
    "category": "Cities",
    "author": "Canvas Era",
    "date": "2026-08-30"
  },
    {
    "title": "Midnight Neon Dreamer",
    "slug": "midnight-neon-dreamer",
    "desc": "A futuristic girl with cybernetic gear sitting on a fire escape, overlooking a rain-soaked, neon-lit metropolis",
    "description": "A futuristic girl with cybernetic gear sitting on a fire escape, overlooking a rain-soaked, neon-lit metropolis",
    "prompt": "​Cyberpunk anime portrait, a girl wearing futuristic cybernetic headphones and a techwear jacket, sitting on a fire escape, rainy night in a futuristic metropolis, reflection of neon signs in wet puddles, soft bokeh city lights in the background, synthwave color palette (neon blue and pink), moody lighting, sharp focus on eyes, ultra-detailed, futuristic urban aesthetic --ar 9:16",
    "image": "images/midnight-neon-dreamer.webp",
    "tags": [],
    "category": "Anime",
    "author": "Canvas Era",
    "date": "2026-08-29"
    },
     {
    "title": "Rainy Day Serenity: A Childhood Memory",
    "slug": "rainy-day-serenity-a-childhood-memory",
    "desc": "Embrace the comfort of a rainy afternoon with this enchanting illustration. Featuring a joyful girl and her faithful white cat amidst a garden of blooming roses, this piece perfectly captures the innocence, warmth, and nostalgia of childhood on a gentle rainy day.",
    "description": "Embrace the comfort of a rainy afternoon with this enchanting illustration. Featuring a joyful girl and her faithful white cat amidst a garden of blooming roses, this piece perfectly captures the innocence, warmth, and nostalgia of childhood on a gentle rainy day.",
    "prompt": "A charming illustration of a joyful little girl with long black hair, smiling, wearing a white dress with red polka dots and red rain boots. She is standing in a lush rose garden, holding a vibrant multi-colored umbrella. A cute white cat sits beside her looking up. Rainy day ambiance, light beige sky background. Art Style: Xiaohongshu illustration style, clear black outlines, warm earth tones (beige, red, dark green), richly detailed roses and foliage, flat illustration style, soft lighting, no harsh shadows, whimsical, 8k, high quality, professional art --ar 2:3",
    "image": "images/rainy-day-serenity-a-childhood-memory.webp",
    "tags": [],
    "category": "Art",
    "author": "Canvas Era",
    "date": "2026-08-29"
  },
    {
    "title": "Paris, Je T'Aime — Travel Scrapbook",
    "slug": "paris-je-taime-travel-scrapbook",
    "desc": "A dreamy Parisian journey filled with café mornings, romantic streets, treasured snapshots, and charming handwritten memories.",
    "description": "A dreamy Parisian journey filled with café mornings, romantic streets, treasured snapshots, and charming handwritten memories.",
    "prompt": "Cozy travel scrapbook collage of a cute young girl traveling through Paris, France, surrounded by vintage Paris Metro tickets, aged postcards, torn paper edges, polaroid photographs, handwritten French notes, postage stamps, tiny coffee receipts, pressed flowers, Eiffel Tower, Arc de Triomphe, Notre-Dame Cathedral, charming Montmartre streets and cozy Parisian café, warm cream and blush color palette, soft golden morning light, delicate paper textures, layered scrapbook composition, nostalgic travel journal aesthetic, highly detailed illustration, whimsical cozy atmosphere, cinematic softness --ar 2:3",
    "image": "images/paris-je-taime-travel-scrapbook.webp",
    "tags": [],
    "category": "Cities",
    "author": "Canvas Era",
    "date": "2026-08-29"
    },
     {
    "title": "Alchemist's Cozy Corner",
    "slug": "alchemists-cozy-corner",
    "desc": "A cozy, cluttered room filled with glowing potion bottles, ancient books, and a little cat wearing a wizard hat",
    "description": "A cozy, cluttered room filled with glowing potion bottles, ancient books, and a little cat wearing a wizard hat",
    "prompt": "​Anime illustration, interior of a cozy witch's alchemy workshop, shelves stacked with glowing colorful potion jars and leather-bound books, soft golden light filtering through a stained glass window, a cute small black cat wearing a tiny wizard hat sitting on a desk, whimsical and magical atmosphere, warm tones, Studio Pierrot style, highly detailed, vibrant colors --ar 4:5",
    "image": "images/alchemists-cozy-corner.webp",
    "tags": [],
    "category": "Anime",
    "author": "Canvas Era",
    "date": "2026-08-29"
     },
            {
    "title": "The Greenhouse Botanist",
    "slug": "the-greenhouse-botanist",
    "desc": "A gentle boy tending to his lush indoor greenhouse, surrounded by hanging plants, sunlight, and a small watering can.",
    "description": "A gentle boy tending to his lush indoor greenhouse, surrounded by hanging plants, sunlight, and a small watering can.",
    "prompt": "Soft digital illustration of a young boy in a sweater tending to an indoor greenhouse, lush hanging plants and vines everywhere, sunbeams streaming through glass windows, cozy cottage-core aesthetic, warm golden light, gentle expression, detailed botanical elements, clean soft lines, warm earth tones, storybook illustration style, high quality --ar 2:3",
    "image": "images/the-greenhouse-botanist.webp",
    "tags": [],
    "category": "Art",
    "author": "Canvas Era",
    "date": "2026-08-29"
            },
    {
    "title": "Prague Postcards — A Fairytale Journey",
    "slug": "prague-postcards-a-fairytale-journey",
    "desc": "A magical Prague stroll filled with cobblestone streets, castle views, charming cafés, old postcards, and dreamy European memories",
    "description": "A magical Prague stroll filled with cobblestone streets, castle views, charming cafés, old postcards, and dreamy European memories",
    "prompt": "Cozy travel scrapbook collage of a cute young girl wandering through Prague, Czech Republic, surrounded by vintage tram tickets, antique postcards, polaroid photographs, handwritten Czech notes, postage stamps, café receipts, pressed flowers, Prague Castle, Charles Bridge, Old Town Square, Astronomical Clock and colorful historic buildings, warm cream, dusty lavender and muted terracotta palette, soft misty morning light, aged paper textures, layered scrapbook elements, nostalgic European travel journal aesthetic, highly detailed illustration, whimsical fairytale atmosphere, cozy cinematic lighting --ar 2:3",
    "image": "images/prague-postcards-a-fairytale-journey.webp",
    "tags": [],
    "category": "Cities",
    "author": "Canvas Era",
    "date": "2026-08-29"
  },
         {
    "title": "The Clockmaker's Apprentice",
    "slug": "the-clockmakers-apprentice",
    "desc": "A boy sitting at a desk filled with gears and clocks, working with a small tool under the warm light of a desk lamp.",
    "description": "A boy sitting at a desk filled with gears and clocks, working with a small tool under the warm light of a desk lamp.",
    "prompt": "Charming digital illustration of a young boy working on a vintage wooden clock at a cluttered wooden desk, surrounded by gears and tools, warm amber desk lamp lighting, cozy rustic workshop, soft shadows, intricate details, gentle focus, warm color palette (browns, creams, gold), storybook illustration, peaceful and focused atmosphere --ar 4:5\"",
    "image": "images/the-clockmakers-apprentice.webp",
    "tags": [],
    "category": "Art",
    "author": "Canvas Era",
    "date": "2026-08-29"
  },
     {
    "title": "Sakura Blade Spirit",
    "slug": "sakura-blade-spirit",
    "desc": "A samurai girl in traditional attire standing amidst a storm of falling cherry blossoms",
    "description": "A samurai girl in traditional attire standing amidst a storm of falling cherry blossoms",
    "prompt": "​Anime illustration, beautiful samurai girl wearing a traditional kimono with intricate floral patterns, standing in the middle of a massive cherry blossom storm, petals flying everywhere, serene expression, sunset lighting, ukiyo-e inspired colors mixed with modern anime style, sharp details, atmospheric, epic composition, ultra-fine art --ar 2:3",
    "image": "images/sakura-blade-spirit.webp",
    "tags": [],
    "category": "Anime",
    "author": "Canvas Era",
    "date": "2026-08-29"
  },
    {
    "title": "Baghdad Memories — The Heart of Mesopotamia",
    "slug": "baghdad-memories-the-heart-of-mesopotamia",
    "desc": "A nostalgic Baghdad journey celebrating ancient heritage, riverside evenings, traditional architecture, warm tea, and beautiful cultural memories.",
    "description": "A nostalgic Baghdad journey celebrating ancient heritage, riverside evenings, traditional architecture, warm tea, and beautiful cultural memories.",
    "prompt": "Cozy travel scrapbook collage of a cute young girl discovering Baghdad, Iraq, surrounded by vintage travel tickets, Iraqi postage stamps, polaroid photographs, handwritten Arabic notes, old paper fragments, traditional tea cups, Al-Mutanabbi Street, Al-Shaheed Monument, Abu Hanifa Mosque, Baghdad old city architecture, Tigris River and traditional wooden boats, subtle Mesopotamian motifs inspired by ancient Babylonian patterns, warm sand, ivory and muted gold palette, soft sunset lighting, textured aged paper, layered scrapbook composition, nostalgic cultural travel journal, highly detailed illustration, peaceful cozy atmosphere --ar 2:3",
    "image": "images/baghdad-memories-the-heart-of-mesopotamia.webp",
    "tags": [],
    "category": "Cities",
    "author": "Canvas Era",
    "date": "2026-08-29"
  },
     {
    "title": "Magical Café in Floating Islands",
    "slug": "magical-caf-in-floating-islands",
    "desc": "A cozy fantasy coffee shop perched on a floating island above the clouds, serving magical creatures.",
    "description": "A cozy fantasy coffee shop perched on a floating island above the clouds, serving magical creatures.",
    "prompt": "A charming anime-style café built on a floating island above cotton candy clouds, outdoor terrace with wooden tables and magical floating lanterns, a friendly witch barista serving glowing latte art to a small dragon and a cat familiar, whimsical fantasy architecture with climbing ivy and flower boxes, sunset golden hour lighting, vibrant colors, detailed background with other floating islands visible, cozy atmosphere, Kyoto Animation style --ar 4:3",
    "image": "images/magical-caf-in-floating-islands.webp",
    "tags": [],
    "category": "Anime",
    "author": "Canvas Era",
    "date": "2026-08-29"
     },
          
  
];
